### PR TITLE
Bug Fix: Cannot enter Admin Menue with buttons

### PR DESCRIPTION
**Pull request by boerge1**
* it was only working with pin as there was an explicite waiting for no button.
  Doing the explicite wait for no button in every case now.

### CODE REVIEW

**Comment by boerge1** [comment]
@xfjx I'm not fully satified with this solution. At the moment there is no reaction when pressing all buttons long until you release the buttons.
Shall I add a 'pling' after the long press is recognized?

**Comment by boerge1** [comment]
Did the above proposed change.

**Comment by xfjx** [comment]
This version is nor working.

E.g. I press three buttons until admin menu is activated (the pling is audible) and then release only the back key.
It says "OK, Vorgang abgebrochen" and after that Shortcut 2 is triggered.


play mp3 262
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
clear folder
clear mp3
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 7
AdmAllow::react() 2
enqueue mp3 802 0
clear folder
clear mp3
SM abort
enter Idle
play current
play mp3 802
Idle::react(b) 4
Base -> StartPlay
enter StartPlay
enqueue mp3 262 0
clear folder
clear mp3
play current
play mp3 262
clear folder
clear mp3
clear folder
clear mp3
clear folder
clear mp3
enqueue 3-2
StartPlay -> Play
enter Play
play current
play 3-2
clear folder
clear mp3
enter Idle

**Comment by boerge1** [comment]
Hmm, strange. I'll check this. Thanks for testing.

**Comment by boerge1** [comment]
Fixed it. Now I implemented the waiting after allLong in the Button class itself. 
This also better fits to the implementation of the command sources.
@xfjx could you please test it again?

**Review by xfjx — APPROVED** [review]
Works now.

Thank you!

**Pull request merged**
