### PR TITLE
Issue 020: add pyttsx3 library support for offline TTS

### PR DESCRIPTION
**Pull request by SteRoh**
solves https://github.com/tonuino/TonUINO-TNG/issues/20

Signed-off-by: steroh <sr118@gmx.de>

### CODE REVIEW

**Comment by SteRoh** [comment]
You are right, the Quality is quite bad.
But on the other hand, there is no option right now if you dont have an aws account nor an google account (that is exactly my case) :(

1. Which OS do you have?

2. Each OS has some build in voices. You can change them manually. Give it a try.

```
        engine = pyttsx3.init();
        voices = engine.getProperty('voices')
        engine.setProperty('voice', voices[0].id) #change index to change voices
```

**Comment by boerge1** [comment]
I'm using arch linux.
The problem seems to be espeak. If I call it directly it generates the same pure files. I tried with all voices.

**Comment by mhioz** [comment]
> You are right, the Quality is quite bad. But on the other hand, there is no option right now if you dont have an aws account nor an google account (that is exactly my case) :(

There is a free offline high quality option. You may use CoquiTTS instead (https://pypi.org/project/TTS/)
It includes the german TTS voice modell "Thorsten-voice". Infos and examples: https://www.thorsten-voice.de/ or at his Youtube channel.

I added the CoquiTTS-Engine to the script at my fork: https://github.com/mhioz/TonUINO/blob/DEV/tools/text_to_speech.py.

**Comment by boerge1** [comment]
@mhioz I tried CoquiTTS with Thorsten and it works fine with good quality. I adapted your changes to the latest version in the main branch. 
Shall I make a pull request based on your changes or do you want to make this?

**Comment by mhioz** [comment]
@boerge1 Please do it the way it is easier for you. I'm not at home at the moment and couldn't set up a pull request (or check if it works) until 25 February, afterwards gladly.

**Comment by boerge1** [comment]
I think we should close this pull request. A better offline variant you can find here #62

**Pull request closed without merging**
